name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # to create releases and tags
  issues: write # to post release notes to related issues
  pull-requests: write # to post release notes to related PRs
  id-token: write # for npm provenance

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Run tests
        env:
          JAPAN_POST_CLIENT_ID: ${{ secrets.JAPAN_POST_CLIENT_ID }}
          JAPAN_POST_SECRET_KEY: ${{ secrets.JAPAN_POST_SECRET_KEY }}
        run: npm run ci-test

      - name: Build
        run: npm run build:clean

      - name: Verify npm authentication
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm whoami
          echo "Current user authenticated successfully"

      - name: Debug package info
        run: |
          echo "Package name: $(npm pkg get name)"
          echo "Package version: $(npm pkg get version)"
          echo "Registry: $(npm config get registry)"
          ls -la dist/
          echo "Files to be published:"
          npm pack --dry-run

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release 